from datetime import datetime


class Metric:
    """
    Represents one metrics snapshot generated by a router.

    Documented Sprint 3 metrics:
    - queue_size
    - packets_forwarded
    - packets_discarded
    """

    def __init__(self, router_id, queue_size, packets_forwarded, packets_discarded):
        self.router_id = router_id
        self.timestamp = datetime.now().isoformat(timespec="seconds")
        self.queue_size = queue_size
        self.packets_forwarded = packets_forwarded
        self.packets_discarded = packets_discarded

    def to_dict(self):
        """
        Convert metric object to dictionary.
        """
        return {
            "router_id": self.router_id,
            "timestamp": self.timestamp,
            "queue_size": self.queue_size,
            "packets_forwarded": self.packets_forwarded,
            "packets_discarded": self.packets_discarded
        }