import json
import mysql.connector

from app.utils.db_config import DB_CONFIG


class RoutingTableDAO:
    """
    DAO responsible for persistence operations related to calculated routing tables.

    Sprint 2 responsibilities:
    - Clear old calculated routes.
    - Save new routing table entries.
    - Retrieve persisted calculated routes.
    """

    def __init__(self):
        self.config = DB_CONFIG

    def connect(self):
        """
        Open a MySQL connection using the controller database configuration.
        """
        return mysql.connector.connect(**self.config)

    def get_router_id_by_name(self, router_name):
        """
        Return the database ID of a router using its name.

        Args:
            router_name (str): Router name, for example R1.

        Returns:
            int | None: Router database ID if found, otherwise None.
        """
        connection = self.connect()
        cursor = connection.cursor(dictionary=True)

        query = """
        SELECT id
        FROM routers
        WHERE nombre = %s
        """
        cursor.execute(query, (router_name,))
        row = cursor.fetchone()

        cursor.close()
        connection.close()

        if row is None:
            return None

        return row["id"]

    def clear_calculated_routes(self):
        """
        Delete all previously calculated routes.

        Sprint 2 recalculates routing tables from the current active topology,
        so old calculated routes are removed before saving the new result.
        """
        connection = self.connect()
        cursor = connection.cursor()

        cursor.execute("DELETE FROM rutas_calculadas")
        connection.commit()

        cursor.close()
        connection.close()

    def save_routing_tables(self, routing_tables, calculation_datetime):
        """
        Save all generated routing tables in MySQL.

        Args:
            routing_tables (dict): Routing tables generated by RoutingTableService.
            calculation_datetime (datetime): Calculation timestamp.

        Returns:
            int: Number of entries saved.
        """
        if not isinstance(routing_tables, dict):
            raise ValueError("Routing tables must be a dictionary.")

        self.clear_calculated_routes()

        saved_entries = 0

        for source_router, table_data in routing_tables.items():
            source_router_id = self.get_router_id_by_name(source_router)

            if source_router_id is None:
                raise ValueError(f"Source router {source_router} does not exist.")

            entries = table_data.get("entries", [])

            for entry in entries:
                destination_router = entry["destination_router"]
                destination_router_id = self.get_router_id_by_name(destination_router)

                if destination_router_id is None:
                    raise ValueError(
                        f"Destination router {destination_router} does not exist."
                    )

                self.save_routing_table_entry(
                    source_router_id=source_router_id,
                    destination_router_id=destination_router_id,
                    destination_prefix=entry["destination_prefix"],
                    prefix_length=entry["prefix_length"],
                    next_hop=entry["next_hop"],
                    cost=entry["cost"],
                    path=entry["path"],
                    calculation_datetime=calculation_datetime
                )

                saved_entries += 1

        return saved_entries

    def save_routing_table_entry(
        self,
        source_router_id,
        destination_router_id,
        destination_prefix,
        prefix_length,
        next_hop,
        cost,
        path,
        calculation_datetime
    ):
        """
        Save one routing table entry.
        """
        connection = self.connect()
        cursor = connection.cursor()

        query = """
        INSERT INTO rutas_calculadas (
            router_origen_id,
            router_destino_id,
            prefijo_destino,
            longitud_prefijo,
            siguiente_salto,
            costo,
            ruta_completa,
            estado,
            fecha_calculo
        )
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
        """

        values = (
            source_router_id,
            destination_router_id,
            destination_prefix,
            prefix_length,
            next_hop,
            cost,
            json.dumps(path),
            "activa",
            calculation_datetime
        )

        cursor.execute(query, values)
        connection.commit()

        cursor.close()
        connection.close()

    def get_all_calculated_routes(self):
        """
        Return all calculated routes with router names instead of only IDs.
        """
        connection = self.connect()
        cursor = connection.cursor(dictionary=True)

        query = """
        SELECT
            rc.id,
            ro.nombre AS router_origen,
            rd.nombre AS router_destino,
            rc.prefijo_destino,
            rc.longitud_prefijo,
            rc.siguiente_salto,
            rc.costo,
            rc.ruta_completa,
            rc.estado,
            rc.fecha_calculo
        FROM rutas_calculadas rc
        INNER JOIN routers ro ON rc.router_origen_id = ro.id
        INNER JOIN routers rd ON rc.router_destino_id = rd.id
        ORDER BY ro.nombre, rd.nombre
        """

        cursor.execute(query)
        routes = cursor.fetchall()

        cursor.close()
        connection.close()

        return routes